Repository AY2425S1-CS2113-T11-1/tp, pull requests merged in 2024-11, with the labels that each got.

#106 Update ppp
  docs/team/lowjunchen.md
Labels: severity.Low

#107 Update PPP
  docs/team/metanyu.md
Labels: Issue.Enhancement

#109 Add JavaDoc to Storage and StateManager & PPP
  .github/workflows/page.yml
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/_config.yml
  docs/team/AjayShanker-geek.md
  docs/team/johndoe.md
  docs/team/kennethszj.md
  docs/team/lowjunchen.md
  docs/team/metanyu.md
  docs/team/ncf3535.md
  src/main/java/seedu/duke/MediTask.java
  src/main/java/seedu/duke/data/state/StateManager.java
  src/main/java/seedu/duke/storage/JsonUtil.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageBackup.java
  src/main/java/seedu/duke/storage/StorageFile.java
  src/main/java/seedu/duke/storage/exception/StorageOperationException.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/storage/JsonUtilTest.java
Labels: Issue.Enhancement, priority.Low

#111 Update DG & UG
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/_config.yml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/help_patient.png
  docs/images/help_task.png
Labels: type.Task, priority.Low

#110 Enhance Documentation and Structure in Patient and Utility Classes
  src/main/java/seedu/duke/commands/AddPatientCommand.java
  src/main/java/seedu/duke/commands/DeletePatientCommand.java
  src/main/java/seedu/duke/commands/FindPatientCommand.java
  src/main/java/seedu/duke/commands/ListPatientCommand.java
  src/main/java/seedu/duke/commands/SelectPatientCommand.java
  src/main/java/seedu/duke/parser/parserutils/DateFormats.java
  src/main/java/seedu/duke/parser/parserutils/DateTimeFormats.java
  src/main/java/seedu/duke/parser/parserutils/TimeFormats.java
  src/test/java/seedu/duke/patient/PatientTest.java
Labels: type.Task, priority.High

#116 Update task-related features for UG and minor formatting change
  docs/UserGuide.md
Labels: Issue.Enhancement

#114 Change class diagram to integrate color scheme of the group
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ParserClass.puml
  docs/diagrams/style.puml
  docs/images/AddTaskSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/ParserClass.png
  src/main/java/seedu/duke/data/state/StateManager.java
  src/main/java/seedu/duke/parser/AddDeadlineParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/input.txt
Labels: Issue.Enhancement, severity.Low

#122 Update clarity of UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#121 Fix exception handling for invalid inputs in DateFormat
  src/main/java/seedu/duke/parser/parserutils/DateFormat.java
Labels: priority.High

#120 Add and update diagrams for developer guide
  docs/diagrams/HospitalClassDiagram.puml
  docs/diagrams/StateManagerClassDiagram.puml
  docs/images/AddPatientSequenceDiagram.png
  docs/images/DeletePatientSequenceDiagram.png
  docs/images/HospitalClassDiagram.png
  docs/images/StateManagerClassDiagram.png
Labels: priority.High

#118 Update Diagram
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/CommandClass.puml
  docs/diagrams/TaskClassDiagram.puml
  docs/images/AddTaskSequenceDiagram.png
  docs/images/CommandClass.png
  docs/images/TaskClassDiagram.png
Labels: Issue.Enhancement

#124 update diagrams based on teacher feedback
  docs/diagrams/CompletionRateSequenceDiagram.puml
  docs/diagrams/StateSwitchingSequenceDiagram.puml
  docs/diagrams/TagPatientClassDiagram.puml
  docs/images/CompletionRateSequenceDiagram.png
  docs/images/StateSwitchingSequenceDiagram.png
  docs/images/TagPatientClassDiagram.png
Labels: priority.High

#128 Resolve Issue #126
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/CommandClass.puml
  docs/diagrams/CompletionRateSequenceDiagram.puml
  docs/diagrams/DeletePatientSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/HospitalClassDiagram.puml
  docs/diagrams/ParseAddTaskSequenceDiagram.puml
  docs/diagrams/ParserClass.puml
  docs/diagrams/StateManagerClassDiagram.puml
  docs/diagrams/StateSwitchingSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/TagPatientClassDiagram.puml
  docs/diagrams/TaskClassDiagram.puml
  docs/images/ParseAddTaskSequenceDiagram.png
Labels: priority.Low

#129 Update images based on scaling
  docs/images/AddPatientSequenceDiagram.png
  docs/images/AddTaskSequenceDiagram.png
  docs/images/ArchitectureDiagram.png
  docs/images/CommandClass.png
  docs/images/CompletionRateSequenceDiagram.png
  docs/images/DeletePatientSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/HospitalClassDiagram.png
  docs/images/ParserClass.png
  docs/images/StateManagerClassDiagram.png
  docs/images/StateSwitchingSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/TagPatientClassDiagram.png
  docs/images/TaskClassDiagram.png
Labels: type.Bug

#133 Refactor diagrams for improved readability
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/diagrams/DeletePatientSequenceDiagram.puml
  docs/diagrams/HospitalClassDiagram.puml
  docs/diagrams/StateManagerClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddPatientSequenceDiagram.png
  docs/images/DeletePatientSequenceDiagram.png
  docs/images/HospitalClassDiagram.png
  docs/images/StateManagerClassDiagram.png
Labels: priority.High

#134 Update the font size, scale and save the images
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ParserClass.puml
  docs/images/AddTaskSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/ParserClass.png
Labels: type.Bug

#207 fix bug where adding a task silently fails
  src/main/java/seedu/duke/data/state/StateManager.java
Labels: priority.High

#211 Add file-based logging and adjust severity level to WARNING
  .gitignore
  src/main/java/seedu/duke/MediTask.java
  src/main/java/seedu/duke/commands/AddPatientCommand.java
  src/main/java/seedu/duke/commands/AddTaskCommand.java
  src/main/java/seedu/duke/commands/BackCommand.java
  src/main/java/seedu/duke/commands/DeletePatientCommand.java
  src/main/java/seedu/duke/commands/DeleteTaskCommand.java
  src/main/java/seedu/duke/commands/FindPatientCommand.java
  src/main/java/seedu/duke/commands/FindTaskCommand.java
  src/main/java/seedu/duke/commands/HospitalCommand.java
  src/main/java/seedu/duke/commands/ListPatientCommand.java
  src/main/java/seedu/duke/commands/ListTaskCommand.java
  src/main/java/seedu/duke/commands/MarkTaskCommand.java
  src/main/java/seedu/duke/commands/SelectPatientCommand.java
  src/main/java/seedu/duke/commands/UnmarkTaskCommand.java
  src/main/java/seedu/duke/data/logger/LoggerConfig.java
  src/main/java/seedu/duke/parser/AddDeadlineParser.java
  src/main/java/seedu/duke/parser/parserutils/DateFormat.java
Labels: priority.High

#210 Fix the following issues
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/parserutils/PatientName.java
  src/main/java/seedu/duke/parser/parserutils/TaskName.java
Labels: priority.Medium

#212 Add Examples to Help Command
  docs/UserGuide.md
  docs/images/StorageClassDiagram.png
  docs/images/help_patient.png
  docs/images/help_task.png
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/common/Messages.java
Labels: Issue.Enhancement, priority.Low

#209 fix cosmetic bug
  src/main/java/seedu/duke/data/hospital/Hospital.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: Issue.Enhancement, priority.Low

#217 Fix Developer Guide Sequence and Class Diagrams
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/diagrams/DeletePatientSequenceDiagram.puml
  docs/diagrams/HospitalClassDiagram.puml
  docs/images/AddPatientSequenceDiagram.png
  docs/images/DeletePatientSequenceDiagram.png
  docs/images/HospitalClassDiagram.png
Labels: priority.High

#222 Fix inaccurate activation bar
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/diagrams/DeletePatientSequenceDiagram.puml
  docs/images/AddPatientSequenceDiagram.png
  docs/images/DeletePatientSequenceDiagram.png
Labels: priority.High

#224 Fix Duplications on JSON
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/duke/MediTask.java
  src/main/java/seedu/duke/data/hospital/Hospital.java
  src/main/java/seedu/duke/storage/JsonUtil.java
  src/main/java/seedu/duke/storage/StorageDeserializer.java
  src/test/java/seedu/duke/data/hospital_data_duplicates.json
  src/test/java/seedu/duke/state/StateManagerTest.java
  src/test/java/seedu/duke/storage/StorageFileTest.java
Labels: Issue.Enhancement, priority.Medium

#227 Fix broken links
  README.md
Labels: priority.Medium

#226 Align AboutUs.md formatting
  docs/AboutUs.md
Labels: priority.Medium

#225 Fix issues
  docs/AboutUs.md
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ParserClass.puml
  docs/diagrams/TagPatientClassDiagram.puml
  docs/images/FindSequenceDiagram.png
  docs/images/ParserClass.png
Labels: priority.Low

#228 Recalculation Completion Rate
  src/main/java/seedu/duke/data/state/StateManager.java
  src/main/java/seedu/duke/data/task/TaskList.java
  src/main/java/seedu/duke/storage/StorageDeserializer.java
Labels: type.Bug, priority.Medium

#230 edit portfolio page url
  docs/AboutUs.md
Labels: type.Bug

#235 Add removed exception message
  src/main/java/seedu/duke/data/state/StateManager.java
Labels: type.Bug, severity.High

#244 Minor UG update
  docs/UserGuide.md
Labels: severity.VeryLow

#250 Update PPP
  docs/team/AjayShanker-geek.md
Labels: type.Task, priority.Low

#251 Rename PPP
  docs/team/ajayshanker-geek.md
Labels: type.Task
