Repository AY2425S1-CS2113-T11-1/tp, pull requests merged in 2024-10, with the labels that each got.

#10 Handle different keywords of commands in Parser class
  build.gradle
  src/main/java/seedu/duke/MediTask.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/exception/Exception.java
  src/main/java/seedu/duke/data/hospital/Patient.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: type.Task, priority.High

#18 Include Unit Tests to ensure workability of program
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: severity.Low

#25 Add support persistent data
  .gitignore
  build.gradle
  data/hospital_data.json
  src/main/java/seedu/duke/data/hospital/Hospital.java
  src/main/java/seedu/duke/data/hospital/Patient.java
  src/main/java/seedu/duke/data/task/Task.java
  src/main/java/seedu/duke/data/task/TaskList.java
  src/main/java/seedu/duke/storage/JsonUtil.java
  src/main/java/seedu/duke/storage/StorageFile.java
  src/test/java/seedu/duke/data/hospital_data_load.json
  src/test/java/seedu/duke/data/hospital_data_save.json
  src/test/java/seedu/duke/storage/JsonUtilTest.java
  src/test/java/seedu/duke/storage/StorageFileTest.java
Labels: type.Task, priority.High

#26 Merge Command return data type
  src/main/java/seedu/duke/commands/AddPatientCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: type.Task

#40 Add Assertions in StorageFile and JsonUtil
  src/main/java/seedu/duke/storage/JsonUtil.java
  src/main/java/seedu/duke/storage/StorageFile.java
Labels: priority.Low

#39 Add Logging Support
  src/main/java/seedu/duke/storage/JsonUtil.java
  src/main/java/seedu/duke/storage/StorageFile.java
Labels: priority.Low

#45 Update parser to include if..else for different states
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.High, severity.High

#46 integrate task command into main function
  src/main/java/seedu/duke/MediTask.java
  src/main/java/seedu/duke/commands/AddTaskCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/DeleteTaskCommand.java
  src/main/java/seedu/duke/commands/ListTaskCommand.java
  src/main/java/seedu/duke/commands/MarkTaskCommand.java
  src/main/java/seedu/duke/commands/TaskCommand.java
  src/main/java/seedu/duke/commands/UnmarkTaskCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/TaskCommandTest.java
Labels: priority.High, severity.High

#50 correctly pass index number to mark, unmark, delete command for task
  src/main/java/seedu/duke/MediTask.java
  src/main/java/seedu/duke/commands/DeletePatientCommand.java
  src/main/java/seedu/duke/commands/DeleteTaskCommand.java
  src/main/java/seedu/duke/commands/ListTaskCommand.java
  src/main/java/seedu/duke/commands/MarkTaskCommand.java
  src/main/java/seedu/duke/commands/UnmarkTaskCommand.java
  src/main/java/seedu/duke/data/task/Task.java
  src/test/java/seedu/duke/commands/TaskCommandTest.java
Labels: type.Bug, severity.High

#57 Fix Exception JSON
  data/hospital_data.json
  src/main/java/seedu/duke/commands/BackCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/storage/JsonUtil.java
  src/main/java/seedu/duke/storage/StorageFile.java
  src/main/java/seedu/duke/ui/Colors.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ui/UiTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/data/hospital_data.json
  text-ui-test/input.txt
  text-ui-test/runtest.sh
Labels: Issue.Enhancement, priority.High

#61 Enable assertions in Gradle build configuration
  build.gradle
Labels: type.Task

#60 Add MANIFEST.MF file for JAR creation
  META-INF/MANIFEST.MF
Labels: type.Task

#70 Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/images/AddPatientSequenceDiagram.png
Labels: type.Task

#71 Additional task type update
  src/main/java/seedu/duke/commands/AddTaskCommand.java
  src/main/java/seedu/duke/commands/FindTaskCommand.java
  src/main/java/seedu/duke/data/task/Deadline.java
  src/main/java/seedu/duke/data/task/Repeat.java
  src/main/java/seedu/duke/data/task/Task.java
  src/main/java/seedu/duke/data/task/TaskList.java
  src/main/java/seedu/duke/data/task/Todo.java
  src/test/java/seedu/duke/commands/TaskCommandTest.java
  src/test/java/seedu/duke/data/task/TaskListTest.java
Labels: Issue.Enhancement

#66 Update tasklist class to have completion rate var
  src/main/java/seedu/duke/data/task/TaskList.java
  src/test/java/seedu/duke/data/task/TaskListTest.java
Labels: Issue.Enhancement

#72 Feature Class Diagram Storage
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/StorageClassDiagram.png
Labels: type.Task, priority.Low

#78 Add FindPatientCommand to support patient search
  src/main/java/seedu/duke/commands/FindPatientCommand.java
  src/main/java/seedu/duke/data/hospital/Hospital.java
  src/test/java/seedu/duke/PatientTest.java
  src/test/java/seedu/duke/commands/PatientCommandTest.java
Labels: type.Task

#82 Add Stage Manager & Fix Storage to support tag feature
  .github/workflows/gradle.yml
  src/main/java/seedu/duke/MediTask.java
  src/main/java/seedu/duke/commands/AddPatientCommand.java
  src/main/java/seedu/duke/commands/DeletePatientCommand.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/ListPatientCommand.java
  src/main/java/seedu/duke/commands/SelectPatientCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/data/exception/InvalidCommandException.java
  src/main/java/seedu/duke/data/exception/UnknownStateFound.java
  src/main/java/seedu/duke/data/hospital/Hospital.java
  src/main/java/seedu/duke/data/hospital/Patient.java
  src/main/java/seedu/duke/data/state/StageManager.java
  src/main/java/seedu/duke/data/state/State.java
  src/main/java/seedu/duke/parser/ExitParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/data/hospital_data_save.json
  src/test/java/seedu/duke/ui/UiTest.java
Labels: type.Bug, severity.High

#89 Add DateFormat and enums for date-time parsing
  src/main/java/seedu/duke/commands/AddPatientCommand.java
  src/main/java/seedu/duke/data/exception/DateParseException.java
  src/main/java/seedu/duke/parser/AddDeadlineParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/parserutils/DateFormat.java
  src/main/java/seedu/duke/parser/parserutils/DateFormats.java
  src/main/java/seedu/duke/parser/parserutils/DateTimeFormats.java
  src/main/java/seedu/duke/parser/parserutils/TimeFormats.java
  src/test/java/seedu/duke/parser/DateFormatTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: Issue.Story, type.Task, priority.Medium

#92 Update Coverage Tests, Include JavaDoc
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTaskClassDiagram.puml
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/ParserClass.puml
  docs/images/AddTaskClassDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/ParserClass.png
  src/main/java/seedu/duke/parser/AddDeadlineParser.java
  src/main/java/seedu/duke/parser/AddParser.java
  src/main/java/seedu/duke/parser/AddRepeatParser.java
  src/main/java/seedu/duke/parser/AddTodoParser.java
  src/main/java/seedu/duke/parser/BackParser.java
  src/main/java/seedu/duke/parser/CommandParser.java
  src/main/java/seedu/duke/parser/DeleteParser.java
  src/main/java/seedu/duke/parser/ExitParser.java
  src/main/java/seedu/duke/parser/FindParser.java
  src/main/java/seedu/duke/parser/ListParser.java
  src/main/java/seedu/duke/parser/MarkParser.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/parser/SelectParser.java
  src/main/java/seedu/duke/parser/UnmarkParser.java
  src/main/java/seedu/duke/parser/parserutils/Find.java
  src/main/java/seedu/duke/parser/parserutils/Index.java
  src/main/java/seedu/duke/parser/parserutils/PatientName.java
  src/main/java/seedu/duke/parser/parserutils/Tag.java
  src/main/java/seedu/duke/parser/parserutils/TaskName.java
  src/test/java/seedu/duke/parser/ParserTest.java
Labels: priority.Medium

#97 Update to DG (Partial)
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/ArchitectureDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/cli_preview.png
Labels: type.Task, severity.Low

#99 DG update: additional sequence diagram for task, class diagram for command and task package
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddTaskSequenceDiagram.puml
  docs/diagrams/CommandClass.puml
  docs/diagrams/ParseAddTaskSequenceDiagram.puml
  docs/diagrams/TaskClassDiagram.puml
  docs/images/AddTaskSequenceDiagram.png
  docs/images/CommandClass.png
  docs/images/ParseAddTaskSequenceDiagram.png
  docs/images/TaskClassDiagram.png
  src/main/java/seedu/duke/data/task/Task.java
Labels: Issue.Enhancement, priority.High

#100 Add Help Command & Update UG
  docs/README.md
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/common/Messages.java
  src/main/java/seedu/duke/parser/HelpParser.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: Issue.Enhancement, severity.Low

#101 DG update: added sequence diagrams for AddPatient and DeletePatient, class diagrams for Hospital, State, and StateManager
  docs/DeveloperGuide.md
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/diagrams/DeletePatientSequenceDiagram.puml
  docs/diagrams/HospitalClassDiagram.puml
  docs/diagrams/StateManagerClassDiagram.puml
  docs/images/AddPatientSequenceDiagram.png
  docs/images/DeletePatientSequenceDiagram.png
  docs/images/HospitalClassDiagram.png
  docs/images/StateManagerClassDiagram.png
Labels: type.Task, priority.High

#102 Developer Guide Update
  docs/DeveloperGuide.md
  docs/diagrams/AddPatientSequenceDiagram.puml
  docs/diagrams/DeletePatientSequenceDiagram.puml
  docs/images/AddPatientSequenceDiagram.png
  docs/images/DeletePatientSequenceDiagram.png
Labels: priority.High

#104 Improve User Guide
  docs/UserGuide.md
Labels: Issue.Enhancement

#103 Create Project Portfolio Page
  docs/team/ncf3535.md
Labels: severity.VeryLow
